#!/usr/bin/osascript

set myupname to do shell script "echo $USER"
set questionadmin to "*EDITHERE* Account Setup Requires Encryption.
Please enter your Password " & myupname & ""
repeat
	try
		set init_pass to text returned of (display dialog questionadmin default answer "" buttons {"OK", "Cancel"} default button 1 with hidden answer)
		set final_pass to text returned of (display dialog "Please verify and re-type your password" buttons {"OK", "Cancel"} default button 1 default answer "" with hidden answer)
		
		if (final_pass is not equal to init_pass) then
			display dialog "Password Incorrect. Please Try Again." with icon stop
		else
			try
				do shell script "ls" user name myupname password init_pass with administrator privileges
				set admin_passwd to final_pass
				exit repeat
			on error err
				display dialog "Password Incorrect. Please Try Again."
				
			end try
		end if
		
	on error number -128
		set canceldialog to display dialog "Cancel was Selected, " & myupname & " is Not Enabled for Filevault 2. You must Enable " & myupname & " for Filevault 2 in Order to Login at Startup." buttons {"OK"} default button 1 with icon stop
		try
			if button returned of canceldialog is "OK" then
				return
			end if
		end try
		
	end try
end repeat

do shell script "touch /Library/Scripts/TempFVPassword.txt"
do shell script "echo " & init_pass & "> " & "/Library/Scripts/TempFVPassword.txt"
